### ISSUE TITLE
I would like to contribute to Searching & Sorting, DP and Mathematics Questions 

### ISSUE THREAD

**Issue by pranshukas** [freakyLuffy/CSES-problem-solutions#3]
## Description 

I would like to contribute solutions to the problems that are left in the Introductory, Searching and Sorting, and DP directory. Also, I would like to add solutions to Mathematics Problems. 

<hr> 

I am new to open source and really keen to learn and contribute. I have solved all the above-mentioned topics question of CSES. I would follow the contribution guidelines. 
Please assign me to work on this.

**Comment by freakyLuffy** [comment]
hello pranshukas, you are free to add any solution which isn't there.  Just make a PR and make sure the assigned folder and file name are same as the original as mentioned on the cses site.
